'use client';

import { useState, useEffect } from 'react';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import { contentApi } from '@/lib/api';

type ContentType = 'all' | 'tips' | 'riddles' | 'facts';

export default function TipsPage() {
    const [content, setContent] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [activeTab, setActiveTab] = useState<ContentType>('all');

    useEffect(() => {
        fetchContent();
    }, [activeTab]);

    async function fetchContent() {
        setLoading(true);
        try {
            let data: any[];
            switch (activeTab) {
                case 'tips':
                    data = await contentApi.getTips(20);
                    break;
                case 'riddles':
                    data = await contentApi.getRiddles(20);
                    break;
                case 'facts':
                    data = await contentApi.getFacts(20);
                    break;
                default:
                    data = await contentApi.getToday();
            }
            setContent(data);
        } catch {
            setContent([]);
        }
        setLoading(false);
    }

    function getBadge(type: string) {
        switch (type) {
            case 'HEALTH_TIP':
                return <span className="content-type-badge badge-tip">Health Tip</span>;
            case 'RIDDLE':
                return <span className="content-type-badge badge-riddle">Riddle</span>;
            case 'FRUIT_FACT':
                return <span className="content-type-badge badge-fact">Fruit Fact</span>;
            default:
                return null;
        }
    }

    const tabs: { key: ContentType; label: string }[] = [
        { key: 'all', label: "Today's Content" },
        { key: 'tips', label: 'Health Tips' },
        { key: 'facts', label: 'Fruit Facts' },
        { key: 'riddles', label: 'Riddles' },
    ];

    return (
        <>
            <Navigation />
            <main style={{ paddingTop: 'var(--header-height)' }}>
                <section className="section">
                    <div className="container" style={{ maxWidth: 800 }}>
                        <span className="hero-tag">AI-Generated Daily</span>
                        <h1 className="section-title">Tips, Facts & Riddles</h1>
                        <hr className="divider" />
                        <p className="section-subtitle">
                            Fresh content generated by our AI every day. Learn about fruits,
                            nutrition, and have fun with riddles.
                        </p>

                        {/* Tabs */}
                        <div style={{ display: 'flex', gap: 8, marginTop: 32, borderBottom: '1px solid var(--color-border)', paddingBottom: 0 }}>
                            {tabs.map((tab) => (
                                <button
                                    key={tab.key}
                                    onClick={() => setActiveTab(tab.key)}
                                    style={{
                                        padding: '10px 20px',
                                        fontSize: '0.88rem',
                                        fontWeight: activeTab === tab.key ? 600 : 400,
                                        color: activeTab === tab.key ? 'var(--color-primary)' : 'var(--color-text-muted)',
                                        borderBottom: activeTab === tab.key ? '2px solid var(--color-primary)' : '2px solid transparent',
                                        marginBottom: -1,
                                        transition: 'all var(--transition-fast)',
                                        background: 'none',
                                    }}
                                >
                                    {tab.label}
                                </button>
                            ))}
                        </div>

                        {/* Content List */}
                        <div style={{ marginTop: 8, background: 'white', borderRadius: 'var(--radius-lg)', border: '1px solid var(--color-border)' }}>
                            {loading ? (
                                Array.from({ length: 3 }).map((_, i) => (
                                    <div key={i} className="content-item">
                                        <div className="skeleton" style={{ width: 80, height: 20, marginBottom: 10 }} />
                                        <div className="skeleton" style={{ width: '60%', height: 22, marginBottom: 8 }} />
                                        <div className="skeleton" style={{ width: '100%', height: 16 }} />
                                    </div>
                                ))
                            ) : content.length > 0 ? (
                                content.map((item) => {
                                    const data = typeof item.content === 'string' ? JSON.parse(item.content) : item.content;
                                    return (
                                        <div key={item.id} className="content-item">
                                            {getBadge(item.type)}
                                            <h3 className="content-title">{data.title || data.question || 'Daily Content'}</h3>
                                            <p className="content-text">
                                                {data.content || data.tip || data.fact || data.hint || ''}
                                            </p>
                                            {data.answer && (
                                                <details style={{ marginTop: 10 }}>
                                                    <summary style={{ cursor: 'pointer', color: 'var(--color-accent)', fontWeight: 500, fontSize: '0.88rem' }}>
                                                        Reveal Answer
                                                    </summary>
                                                    <p style={{ marginTop: 8, color: 'var(--color-text-light)', fontSize: '0.92rem' }}>
                                                        {data.answer}
                                                    </p>
                                                </details>
                                            )}
                                            <div className="content-meta">
                                                <span>{new Date(item.createdAt).toLocaleDateString('en-NG', { dateStyle: 'medium' })}</span>
                                                {item.likes > 0 && <span>{item.likes} likes</span>}
                                            </div>
                                        </div>
                                    );
                                })
                            ) : (
                                <div style={{ padding: 60, textAlign: 'center', color: 'var(--color-text-muted)' }}>
                                    <p>No content available yet. Check back soon!</p>
                                </div>
                            )}
                        </div>
                    </div>
                </section>
            </main>
            <Footer />
        </>
    );
}
